const data = {
    products: [

      {
        id: 0,
        productName: 'skin tight top',
        slug: 'skin-tight-top',
        shortDescription: 'Crush Small Chain Bag Quilted in silver metallized crushed calfskin, aged-silver hardware',
        longDescription: '• Dimensions : L9,8 x H5,9 x W3,1 inch • Metallized crushed calfskin and quilted • Chain bag • Curvilinear base • Shoulder and crossbody chain strap (19,6 inch) • Aged-silver B logo hardware • Studded magnet closure • 3 compartments • 1 inner zipped pocket • 1 inner flat pocket • Nappa lambskin lining • Made in Italy • Wipe with a soft cloth Material: 100% calfskin Product ID: 716351210IW8110',
        productImage: '/images/a.jpg',
        productImage2: '/images/aback.jpg',
        productPrice: 3,
        productColor: 'silver',
        palette: 'bg-[#16dd31]',
        color: "[#50d71e]",
        productSize: 'U',
        countInStock: 838,
        type: 'tops',
      },
      {
        id: 1,
        productName: 'KNIFE BOOTIE',
        slug: 'knife-bootie',
        shortDescription: 'Extreme pointed toe spandex bootie',
        longDescription: '• Dimensions : L9,8 x H5,9 x W3,1 inch • Crushed calfskin and quilted • Chain bag • Curvilinear base • Shoulder and crossbody chain strap (19,6 inch) • Aged-silver B logo hardware • Studded magnet closure • 3 compartments • 1 inner zipped pocket • 1 inept flat pocket • Nappa lambskin lining • Made in Italy • Wipe with a soft cloth Material: 100% calfskin Product ID: 716351210J05812',
        productImage: '/images/d.jpg',
        productImage2: '/images/bback.jpg',
        productPrice: 2,
        productColor: 'silver',
        palette: 'bg-[#16dd31]',
        productSize: 'U',
        countInStock: 194,
        type: 'shoes',
      },
      {
        id: 2,
        productName: 'blanket square xl',
        slug: 'blanket-square-xl',
        shortDescription: 'Crush Small Chain Bag Quilted in silver metallized crushed calfskin, aged-silver hardware ',
        longDescription: '• Dimensions : L9,8 x H5,9 x W3,1 inch • Crushed calfskin and quilted • Chain bag • Curvilinear base • Shoulder and crossbody chain strap (19,6 inch) • Aged-silver B logo hardware • Studded magnet closure • 3 compartments • 1 inner zipped pocket • 1 inept flat pocket • Nappa lambskin lining • Made in Italy • Wipe with a soft cloth Material: 100% calfskin Product ID: 716351210J05812',
        productImage: '/images/k.jpg',
        productImage2: '/images/kback.jpg',
        productPrice: 1,
        productColor: 'white',
        palette: 'bg-[#fa6a45]',
        productSize: 'U',
        countInStock: 194,
        type: 'Shoulder bags',
      },
      {
        id: 3,
        productName: 'chain necklace',
        slug: 'chain-necklace',
        shortDescription: 'Crush Small Chain Bag Quilted in silver metallized crushed calfskin, aged-silver hardware ',
        longDescription: '• Dimensions : L9,8 x H5,9 x W3,1 inch • Crushed calfskin and quilted • Chain bag • Curvilinear base • Shoulder and crossbody chain strap (19,6 inch) • Aged-silver B logo hardware • Studded magnet closure • 3 compartments • 1 inner zipped pocket • 1 inept flat pocket • Nappa lambskin lining • Made in Italy • Wipe with a soft cloth Material: 100% calfskin Product ID: 716351210J05812',
        productImage: '/images/na.jpg',
        productImage2: '/images/na.jpg',
        productPrice: 100,
        productColor: 'green',
        palette: 'bg-[#e4b689]',
        productSize: 'U',
        countInStock: 194,
        type: 'handbags',
      },

      {
        id: 4,
        productName: 'windbreaker',
        slug: 'windbreaker',
        shortDescription: 'Crush Small Chain Bag Quilted in silver metallized crushed calfskin, aged-silver hardware ',
        longDescription: '• Dimensions : L9,8 x H5,9 x W3,1 inch • Crushed calfskin and quilted • Chain bag • Curvilinear base • Shoulder and crossbody chain strap (19,6 inch) • Aged-silver B logo hardware • Studded magnet closure • 3 compartments • 1 inner zipped pocket • 1 inept flat pocket • Nappa lambskin lining • Made in Italy • Wipe with a soft cloth Material: 100% calfskin Product ID: 716351210J05812',
        productImage: '/images/c.jpg',
        productImage2: '/images/c.jpg',
        productPrice: 100,
        productColor: 'green',
        palette: 'bg-[#d92c26]',
        productSize: 'U',
        countInStock: 194,
        type: 'jewelry',
      },

      {
        id: 5,
        productName: 'ruffles gloves',
        slug: 'ruffles-gloves',
        shortDescription: 'Crush Small Chain Bag Quilted in silver metallized crushed calfskin, aged-silver hardware ',
        longDescription: '• Dimensions : L9,8 x H5,9 x W3,1 inch • Crushed calfskin and quilted • Chain bag • Curvilinear base • Shoulder and crossbody chain strap (19,6 inch) • Aged-silver B logo hardware • Studded magnet closure • 3 compartments • 1 inner zipped pocket • 1 inept flat pocket • Nappa lambskin lining • Made in Italy • Wipe with a soft cloth Material: 100% calfskin Product ID: 716351210J05812',
        productImage: '/images/bak.jpg',
        productImage2: '/images/bak.jpg',
        productPrice: 100,
        productColor: 'green',
        palette: 'bg-[#fdc8d6]',
        productSize: 'U',
        countInStock: 194,
        type: 'Shoulder bags',
      },

      {
        id: 6,
        productName: 'knife over-the-knee boots',
        slug: 'knife-over-the-knee-boots',
        shortDescription: 'Crush Small Chain Bag Quilted in silver metallized crushed calfskin, aged-silver hardware ',
        longDescription: '• Dimensions : L9,8 x H5,9 x W3,1 inch • Crushed calfskin and quilted • Chain bag • Curvilinear base • Shoulder and crossbody chain strap (19,6 inch) • Aged-silver B logo hardware • Studded magnet closure • 3 compartments • 1 inner zipped pocket • 1 inept flat pocket • Nappa lambskin lining • Made in Italy • Wipe with a soft cloth Material: 100% calfskin Product ID: 716351210J05812',
        productImage: '/images/f.jpg',
        productImage2: '/images/f.jpg',
        productPrice: 100,
        productColor: 'green',
        palette: 'bg-[#a348cb]',
        productSize: 'U',
        countInStock: 194,
        type: 'Shoulder bags',
      },

      {
        id: 7,
        productName: 'air hobo l',
        slug: 'air-hobo-l',
        shortDescription: 'Crush Small Chain Bag Quilted in silver metallized crushed calfskin, aged-silver hardware ',
        longDescription: '• Dimensions : L9,8 x H5,9 x W3,1 inch • Crushed calfskin and quilted • Chain bag • Curvilinear base • Shoulder and crossbody chain strap (19,6 inch) • Aged-silver B logo hardware • Studded magnet closure • 3 compartments • 1 inner zipped pocket • 1 inept flat pocket • Nappa lambskin lining • Made in Italy • Wipe with a soft cloth Material: 100% calfskin Product ID: 716351210J05812',
        productImage: '/images/baz.jpg',
        productImage2: '/images/baz.jpg',
        palette: 'bg-[#b92929]',
        productPrice: 100,
        productColor: 'green',
        productSize: 'U',
        countInStock: 194,
        type: 'Shoulder bags',
      },

      {
        id: 8,
        productName: 'boxy harrington jacket',
        slug: 'boxy-harrington-jacket',
        shortDescription: 'Crush Small Chain Bag Quilted in silver metallized crushed calfskin, aged-silver hardware ',
        longDescription: '• Dimensions : L9,8 x H5,9 x W3,1 inch • Crushed calfskin and quilted • Chain bag • Curvilinear base • Shoulder and crossbody chain strap (19,6 inch) • Aged-silver B logo hardware • Studded magnet closure • 3 compartments • 1 inner zipped pocket • 1 inept flat pocket • Nappa lambskin lining • Made in Italy • Wipe with a soft cloth Material: 100% calfskin Product ID: 716351210J05812',
        productImage: '/images/b.jpg',
        productImage2: '/images/b.jpg',
        productPrice: 100,
        productColor: 'green',
        palette: 'bg-[#d4ccc2]',
        productSize: 'U',
        countInStock: 194,
        type: 'Shoulder bags',
      },

      {
        id: 9,
        productName: 'air hobo',
        slug: 'air-hobo',
        shortDescription: 'Crush Small Chain Bag Quilted in silver metallized crushed calfskin, aged-silver hardware ',
        longDescription: '• Dimensions : L9,8 x H5,9 x W3,1 inch • Crushed calfskin and quilted • Chain bag • Curvilinear base • Shoulder and crossbody chain strap (19,6 inch) • Aged-silver B logo hardware • Studded magnet closure • 3 compartments • 1 inner zipped pocket • 1 inept flat pocket • Nappa lambskin lining • Made in Italy • Wipe with a soft cloth Material: 100% calfskin Product ID: 716351210J05812',
        productImage: '/images/ee.jpg',
        productImage2: '/images/ee.jpg',
        productPrice: 100,
        productColor: 'green',
        palette: 'bg-[#f96302]',
        productSize: 'U',
        countInStock: 194,
        type: 'Shoulder bags',
      },

      {
        id: 10,
        productName: 'sun pilot earrings',
        slug: 'crush-small-chain-bag-metallized-quilted',
        shortDescription: 'Crush Small Chain Bag Quilted in silver metallized crushed calfskin, aged-silver hardware ',
        longDescription: '• Dimensions : L9,8 x H5,9 x W3,1 inch • Crushed calfskin and quilted • Chain bag • Curvilinear base • Shoulder and crossbody chain strap (19,6 inch) • Aged-silver B logo hardware • Studded magnet closure • 3 compartments • 1 inner zipped pocket • 1 inept flat pocket • Nappa lambskin lining • Made in Italy • Wipe with a soft cloth Material: 100% calfskin Product ID: 716351210J05812',
        productImage: '/images/abi.jpg',
        productImage2: '/images/abi.jpg',
        productPrice: 100,
        productColor: 'green',
        palette: 'bg-[#0065c8]',
        productSize: 'U',
        countInStock: 194,
        type: 'Shoulder bags',
      },

      {
        id: 11,
        productName: 'ice skater top',
        slug: 'ice-skater-top',
        shortDescription: 'Crush Small Chain Bag Quilted in silver metallized crushed calfskin, aged-silver hardware ',
        longDescription: '• Dimensions : L9,8 x H5,9 x W3,1 inch • Crushed calfskin and quilted • Chain bag • Curvilinear base • Shoulder and crossbody chain strap (19,6 inch) • Aged-silver B logo hardware • Studded magnet closure • 3 compartments • 1 inner zipped pocket • 1 inept flat pocket • Nappa lambskin lining • Made in Italy • Wipe with a soft cloth Material: 100% calfskin Product ID: 716351210J05812',
        productImage: '/images/37991561EB_12_a_g.jpg',
        productImage2: '/images/37991561EB_12_a_g.jpg',
        productPrice: 100,
        productColor: 'green',
        palette: 'bg-black',
        productSize: 'U',
        countInStock: 194,
        type: 'Shoulder bags',
      },

      {
        id: 12,
        productName: 'blanket square s',
        slug: 'blanket-square-s',
        shortDescription: 'Crush Small Chain Bag Quilted in silver metallized crushed calfskin, aged-silver hardware ',
        longDescription: '• Dimensions : L9,8 x H5,9 x W3,1 inch • Crushed calfskin and quilted • Chain bag • Curvilinear base • Shoulder and crossbody chain strap (19,6 inch) • Aged-silver B logo hardware • Studded magnet closure • 3 compartments • 1 inner zipped pocket • 1 inept flat pocket • Nappa lambskin lining • Made in Italy • Wipe with a soft cloth Material: 100% calfskin Product ID: 716351210J05812',
        productImage: '/images/kk.jpg',
        productImage2: '/images/kk.jpg',
        productPrice: 100,
        productColor: 'green',
        palette: 'bg-black',
        productSize: 'U',
        countInStock: 194,
        type: 'Shoulder bags',
      },

      {
        id: 13,
        productName: 'knife bootie',
        slug: 'knife-bootie',
        shortDescription: 'Crush Small Chain Bag Quilted in silver metallized crushed calfskin, aged-silver hardware ',
        longDescription: '• Dimensions : L9,8 x H5,9 x W3,1 inch • Crushed calfskin and quilted • Chain bag • Curvilinear base • Shoulder and crossbody chain strap (19,6 inch) • Aged-silver B logo hardware • Studded magnet closure • 3 compartments • 1 inner zipped pocket • 1 inept flat pocket • Nappa lambskin lining • Made in Italy • Wipe with a soft cloth Material: 100% calfskin Product ID: 716351210J05812',
        productImage: '/images/e.jpg',
        productImage2: '/images/e.jpg',
        productPrice: 100,
        productColor: 'green',
        palette: 'bg-[#fd8e01]',
        productSize: 'U',
        countInStock: 194,
        type: 'Shoulder bags',
      },
    ],
  };
  
  export default data;