const data = {
    products: [

      {
        id: 0,
        productName: 'Bottle [85 x 300 mm]',
        slug: 'bottle-85-x-300-mm-matte-natural',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HP029_04-500x750.jpg',
        slugImage: '/images/HP029.jpg',
        productPrice: '€ 82',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 145 x H 55 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },
      {
        id: 1,
        productName: 'Bottle [85 x 300 mm]',
        slug: 'bottle-85-x-300-mm-matte-black',
        longDescription: 'The Hasami Porcelain matte black bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HPB029_01_-500x750.jpg',
        slugImage: '/images/HPB029.jpg',
        productPrice: '€ 82',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 145 x H 72 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },
      {
        id: 2,
        productName: 'Bottle [85 x 300 mm]',
        slug: 'bottle-85-x-300-mm-glazed-grey',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HPM029_01_-500x750.jpg',
        slugImage: '/images/HPM029.jpg',
        productPrice: '',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 145 x H 55 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: 'Out of stock',
      },
      {
        id: 3,
        productName: 'Wooden Coaster / Lid [85 x 21 mm]',
        slug: 'wooden-coaster-lid-85-x-21-mm',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HP022_01_-500x750.jpg',
        slugImage: '/images/HP022.jpg',
        productPrice: '€ 30',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 145 x H 55 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },

      {
        id: 4,
        productName: 'Wooden Tray / Lid [145 x 21 mm]',
        slug: 'wooden-tray-lid-145-x-21-mm',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HP023_-500x750.jpg',
        slugImage: '/images/HP025.jpg',
        productPrice: '€ 68',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 145 x H 55 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },

      {
        id: 5,
        productName: 'Wooden Tray / Lid [220 x 21 mm]',
        slug: 'wooden-tray-lid-220-x-21-mm',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HP025_01_-500x750.jpg',
        slugImage: '/images/HP027.jpg',
        productPrice: '',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 145 x H 55 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: 'Out of stock',
      },

      {
        id: 6,
        productName: 'Serving Bowl [255 x 55 mm]',
        slug: 'serving-bowl-255-x-55-mm-matte-black',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HPB011_01_-500x750.jpg',
        slugImage: '/images/HPB011.jpg',
        productPrice: '€ 114',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 255 x H 55 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },

      {
        id: 7,
        productName: 'Side Plate / Lid [145 x 21 mm]',
        slug: 'side-plate-lid-145-x-21-mm-matte-natural',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HP002_01_-500x750.jpg',
        slugImage: '/images/HP002.jpg',
        productPrice: '€ 27',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 145 x H 21 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },

      {
        id: 8,
        productName: 'Side Plate / Lid [145 x 21 mm]',
        slug: 'side-plate-lid-145-x-21-mm-matte-black',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HPB002_01_-500x750.jpg',
        slugImage: '/images/HPB002.jpg',
        productPrice: '€ 27',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 145 x H 21 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },

      {
        id: 9,
        productName: 'Side Plate / Lid [145 x 21 mm]',
        slug: 'side-plate-lid-145-x-21-mm-glazed-grey',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HPM002_02_-500x750.jpg',
        slugImage: '/images/HPM002.jpg',
        productPrice: '',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 145 x H 21 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: 'Out of stock',
      },

      {
        id: 10,
        productName: 'Soup Bowl [185 x 55 mm]',
        slug: 'soup-bowl-185-x-55-mm-matt-natural',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HP032_01_-500x750.jpg',
        slugImage: '/images/HP033.jpg',
        productPrice: '€ 61',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 185 x H 55 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },

      {
        id: 11,
        productName: 'Soup Bowl [185 x 55 mm]',
        slug: 'round-soup-bowl-185-x-55-mm-matte-black',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HPB032_01_-500x750.jpg',
        slugImage: '/images/HPB033.jpg',
        productPrice: '€ 61',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 185 x H 55 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },

      {
        id: 12,
        productName: 'Soup Bowl [185 x 55 mm]',
        slug: 'soup-bowl-185-x-55-mm-glazed-grey',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HPM032_01_-500x750.jpg',
        slugImage: '/images/HPM033.jpg',
        productPrice: '€ 61',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 185 x H 55 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },

      {
        id: 13,
        productName: 'Sugar Bowl [85 x 55 mm]',
        slug: 'sugar-bowl-85-x-55-mm-matte-natural',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HP017_01_-500x750.jpg',
        slugImage: '/images/HP017.jpg',
        productPrice: '€ 31',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 85 x H 55 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },

      {
        id: 14,
        productName: 'Sugar Bowl [85 x 55 mm]',
        slug: 'sugar-bowl-85-x-55-mm-matte-black',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HPB017_01_-500x750.jpg',
        slugImage: '/images/HPB017.jpg',
        productPrice: '€ 31',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 85 x H 55 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },

      {
        id: 15,
        productName: 'Sugar Bowl [85 x 55 mm]',
        slug: 'sugar-bowl-85-x-55-mm-glazed-grey',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HPM017_01_-500x750.jpg',
        slugImage: '/images/HPM017.jpg',
        productPrice: '€ 31',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 85 x H 55 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },

      {
        id: 16,
        productName: 'Teapot [145 x 106 mm]',
        slug: 'teapot-145-x-106-mm-matte-natural',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HP018_01_-500x750.jpg',
        slugImage: '/images/HP018.jpg',
        productPrice: '€ 132',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 145 x H 106 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',

      },

      {
        id: 17,
        productName: 'Teapot [145 x 106 mm]',
        slug: 'teapot-145-x-106-mm-matte-black',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HPB018_01_-500x750.jpg',
        slugImage: '/images/HPB018.jpg',
        productPrice: '€ 132',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 145 x H 106 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },

      {
        id: 18,
        productName: 'Teapot [145 x 106 mm]',
        slug: 'teapot-145-x-106-mm-glazed-grey',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HPM018_01_-500x750.jpg',
        slugImage: '/images/HPM018.jpg',
        productPrice: '€ 132',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 145 x H 106 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },

      {
        id: 19,
        productName: 'Teapot with Strainer [85 x 160 mm]',
        slug: 'teapot-with-strainer-85-x-160-mm-matte-natural',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HP037_01_-500x750.jpg',
        slugImage: '/images/HP037.jpg',
        productPrice: '€ 111',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 85 x H 160 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },

      {
        id: 20,
        productName: 'Teapot with Strainer [85 x 160 mm]',
        slug: 'teapot-with-strainer-85-x-160-mm-matte-black',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HPB037_01_-500x750.jpg',
        slugImage: '/images/HPB037.jpg',
        productPrice: '€ 111',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 85 x H 160 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },

      {
        id: 21,
        productName: 'Teapot with Strainer [85 x 160 mm]',
        slug: 'teapot-with-strainer-85-x-160-mm-glazed-grey',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HPM037_01_-500x750.jpg',
        slugImage: '/images/HPM037.jpg',
        productPrice: '€ 111',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 85 x H 160 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },

      {
        id: 22,
        productName: 'Tumbler / Utensil Holder [85 x 106 mm]',
        slug: 'tumbler-utensil-holder-85-x-106-mm-matte-natura',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HP038_01_-500x750.jpg',
        productPrice: '€ 41',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 85 x H 106 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },

      {
        id: 23,
        productName: 'Tumbler / Utensil Holder [85 x 106 mm]',
        slug: 'tumbler-utensil-holder-85-x-106-mm-matte-black',
        longDescription: 'The Hasami Porcelain matte natural bowl is made from a mixture of clay and porcelain according to ancient Japanese traditions. It is part of an elaborate series of modular and stackable tableware. Hasami Porcelain was designed by Takuhiro Shinomoto of Tortoise Studios in Los Angeles. It is manufactured in Hasami, a small historic Japanese town located in the Nagasaki prefecture, where porcelain has been crafted since the Edo period for over 400 years ago. Due to the traditional craftsmanship that goes into producing Hasami Porcelain, variations in colour and texture may be present and adds to the uniqueness of each piece.',
        productImage: '/images/TypeO_Hasami_HPB038_01_-500x750.jpg',
        productPrice: '€ 41',
        productMaterial: 'Natural clay and porcelain mix.',
        productDimension: "Dimensions: Ø 85 x H 106 mm.",
        productUsage: 'Usage: Hasami Porcelain is dishwasher safe and microwaveable. Do not use over an open flame or in a regular oven.',
        countInStock: '',
      },
      
    ],
  };
  
  export default data;